package com.senla.bookstore.view;

public enum TitleOfMenuItems {
    SHOW_BOOK_SORTED_BY_AUTHOR,
    SHOW_BOOKS_IN_STOCK,
    SORT_BOOKS_SORTED_BY_AUTHOR,
    SORT_BOOKS_BY_AVAILABILITY_IN_STOCK,
    SORT_BOOKS_BY_DATE_OF_ARRIVE;

}
