-- MySQL Script generated by MySQL Workbench
-- Tue Aug 25 18:14:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BookStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BookStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BookStore` DEFAULT CHARACTER SET utf8 ;
USE `BookStore` ;

-- -----------------------------------------------------
-- Table `BookStore`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `age` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idCustomer_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_of_order` DATE NOT NULL,
  `date_of_done_order` DATE NULL,
  `price_of_order` DECIMAL NOT NULL,
  `order_status` ENUM("NEW", "DONE", "CANCELLED") NOT NULL,
  `id_customer` INT NOT NULL,
  INDEX `customer_to_order_idx` (`id_customer` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_Order_UNIQUE` (`id` ASC),
  CONSTRAINT `customer_to_order`
    FOREIGN KEY (`id_customer`)
    REFERENCES `BookStore`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  `book_status` ENUM("IN_STOCK", "OUT_OF_STOCK", "STALE") NOT NULL,
  `arrive_date` DATE NOT NULL,
  `publication_date` DATE NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_Book_UNIQUE` (`id` ASC),
  INDEX `fk_book_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_book_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `BookStore`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`requestForBook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`requestForBook` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_book` INT NOT NULL,
  `requestForBook_status` ENUM("ACTIVE", "COMPLETED", "CANCELLED") NOT NULL,
  `id_order` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_RequestForBook_UNIQUE` (`id` ASC),
  INDEX `order_to_requestForBook_idx` (`id_order` ASC),
  CONSTRAINT `order_to_requestForBook`
    FOREIGN KEY (`id_order`)
    REFERENCES `BookStore`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
