-- MySQL Script generated by MySQL Workbench
-- Fri Aug  7 14:48:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Store` DEFAULT CHARACTER SET utf8 ;
USE `Store` ;

-- -----------------------------------------------------
-- Table `Store`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Store`.`product` (
  `maker` VARCHAR(10) NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`model`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Store`.`pc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Store`.`pc` (
  `code` INT NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `speed` SMALLINT(8) NOT NULL,
  `ram` SMALLINT(8) NOT NULL,
  `hd` REAL NOT NULL,
  `cd` VARCHAR(10) NOT NULL,
  `price` DECIMAL(10) NULL,
  PRIMARY KEY (`code`),
  INDEX `product_idx` (`model` ASC),
  CONSTRAINT `product`
    FOREIGN KEY (`model`)
    REFERENCES `Store`.`product` (`model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Store`.`laptop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Store`.`laptop` (
  `code` INT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `speed` SMALLINT(10) NOT NULL,
  `ram` SMALLINT(10) NOT NULL,
  `hd` REAL NOT NULL,
  `price` DECIMAL(10) NULL,
  `screen` TINYINT(10) NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `laptop_idx` (`model` ASC),
  CONSTRAINT `laptop`
    FOREIGN KEY (`model`)
    REFERENCES `Store`.`product` (`model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Store`.`printer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Store`.`printer` (
  `code` INT NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `color` CHAR(1) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `price` DECIMAL(10) NULL,
  PRIMARY KEY (`code`),
  INDEX `printer_idx` (`model` ASC),
  CONSTRAINT `printer`
    FOREIGN KEY (`model`)
    REFERENCES `Store`.`product` (`model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
